AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Globals:
  Function:
    MemorySize: 2048
    Timeout: 30

Resources:
  layer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: schrome_arm
      ContentUri: code/
      CompatibleArchitectures:
        - arm64
      CompatibleRuntimes:
        - nodejs14.x
        - nodejs16.x

  node14:
    Type: AWS::Serverless::Function
    Properties:
      Layers:
        - !Ref layer
      Handler: handlers/index.handler
      Runtime: nodejs14.x
      Architectures:
        - arm64
      Policies:
        - AWSLambdaBasicExecutionRole
        - AWSXRayDaemonWriteAccess
      Tracing: Active
  node16:
    Type: AWS::Serverless::Function
    Properties:
      Layers:
        - !Ref layer
      Handler: handlers/index.handler
      Runtime: nodejs16.x
      Architectures:
        - arm64
      Policies:
        - AWSLambdaBasicExecutionRole
        - AWSXRayDaemonWriteAccess
      Tracing: Active
