AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Globals:
  Function:
    MemorySize: 2048
    Timeout: 30

Resources:

  node14:
    Type: AWS::Serverless::Function
    Properties:
      Layers:
        - arn:aws:lambda:us-east-1:863441837526:layer:sparticuz-chrome-aws-lambda:2
      Handler: handlers/index.handler
      Runtime: nodejs14.x
      Policies:
        - AWSLambdaBasicExecutionRole
  node16:
    Type: AWS::Serverless::Function
    Properties:
      Layers:
        - arn:aws:lambda:us-east-1:863441837526:layer:sparticuz-chrome-aws-lambda:2
      Handler: handlers/index.handler
      Runtime: nodejs16.x
      Policies:
        - AWSLambdaBasicExecutionRole
